
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" cacheDuration="PT604800S" entityID="https://stream.onepercentclub.com/sso/saml/metadata/" validUntil="2015-08-21T19:41:52Z">
<md:SPSSODescriptor AuthnRequestsSigned="false" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
<md:KeyDescriptor xmlns:ds="http://www.w3.org/2000/09/xmldsig#" use="signing">
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIEujCCA6KgAwIBAgIJAJfvTxG/az/FMA0GCSqGSIb3DQEBBQUAMIGZMQswCQYDVQQGEwJOTDEWMBQGA1UECBMNTm9vcmQgSG9sbGFuZDESMBAGA1UEBxMJQW1zdGVyZGFtMQ8wDQYDVQQKFAYxJUNsdWIxIjAgBgNVBAMTGXN0cmVhbS5vbmVwZXJjZW50Y2x1Yi5jb20xKTAnBgkqhkiG9w0BCQEWGmRldnRlYW1Ab25lcGVyY2VudGNsdWIuY29tMB4XDTE1MDgwNjEyMjgxNloXDTE2MDgwNTEyMjgxNlowgZkxCzAJBgNVBAYTAk5MMRYwFAYDVQQIEw1Ob29yZCBIb2xsYW5kMRIwEAYDVQQHEwlBbXN0ZXJkYW0xDzANBgNVBAoUBjElQ2x1YjEiMCAGA1UEAxMZc3RyZWFtLm9uZXBlcmNlbnRjbHViLmNvbTEpMCcGCSqGSIb3DQEJARYaZGV2dGVhbUBvbmVwZXJjZW50Y2x1Yi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvhS960dQQISseIN3ZAW2nUZok5nFVmseKoBwA+TssOeaWwHe//2DJaiJlFqE26VcN4XIrnUru9q0hDGgeLDwX2/g3y43LtFgVag3eWLRAnmP8opvwALN1YDRPHcWS00koCdnmtrRdkefA+5pjQc01lXAnrCrTFU/qSbKkGGwbGpoc3uzqb7d+KgpHJyTyNhVN+ac7XdCg2EVWSg3VCUEqKRk7EXo/H2at8EEuOnrJwd3nGJON6GY+lWEqDAd29jz9uFSGGGCxWRPPr1EJj6U7HpffsL1Cl7tSrlWeE1/2uOnXUSceKCwYOvcDIvzVQLXPadvPH8OQJg7dSgPukgZbAgMBAAGjggEBMIH+MB0GA1UdDgQWBBQoHEToHyvXLxLyYQipE6n6bWEmQDCBzgYDVR0jBIHGMIHDgBQoHEToHyvXLxLyYQipE6n6bWEmQKGBn6SBnDCBmTELMAkGA1UEBhMCTkwxFjAUBgNVBAgTDU5vb3JkIEhvbGxhbmQxEjAQBgNVBAcTCUFtc3RlcmRhbTEPMA0GA1UEChQGMSVDbHViMSIwIAYDVQQDExlzdHJlYW0ub25lcGVyY2VudGNsdWIuY29tMSkwJwYJKoZIhvcNAQkBFhpkZXZ0ZWFtQG9uZXBlcmNlbnRjbHViLmNvbYIJAJfvTxG/az/FMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAIkr8M21/Jyd/d+ZyvJfjZ/QgZp41RJGVVnLQ3eQC8cCqPqF/Cpc1Tt4ayaZhgyJxmcfKoM1ssgKAnjeyCodGxlJ1ai+LViQoYJuslu05i6MC9QUHxSncucjtlYL7K0rHegDR3wLd8XOCB7zgR74LpCpINRu2LbODI8jLBGkevOCBwztpRLgoqq3qNYus5VHUvtrlQW+3MmFKNDkLnRs8AJdlewQUuRdPdTKMBfvPIao2Kl15XTTpTN+lUALLstMFPrV9gHjWBwVzlPAwvIw7x0271/vm6oFCa44+1wmkrLj9eyhX+Jse12UZtXlpJzY4yVqGqoFTJLDOPHmvNg+uDM=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:KeyDescriptor xmlns:ds="http://www.w3.org/2000/09/xmldsig#" use="encryption">
<ds:KeyInfo>
<ds:X509Data>
<ds:X509Certificate>
MIIEujCCA6KgAwIBAgIJAJfvTxG/az/FMA0GCSqGSIb3DQEBBQUAMIGZMQswCQYDVQQGEwJOTDEWMBQGA1UECBMNTm9vcmQgSG9sbGFuZDESMBAGA1UEBxMJQW1zdGVyZGFtMQ8wDQYDVQQKFAYxJUNsdWIxIjAgBgNVBAMTGXN0cmVhbS5vbmVwZXJjZW50Y2x1Yi5jb20xKTAnBgkqhkiG9w0BCQEWGmRldnRlYW1Ab25lcGVyY2VudGNsdWIuY29tMB4XDTE1MDgwNjEyMjgxNloXDTE2MDgwNTEyMjgxNlowgZkxCzAJBgNVBAYTAk5MMRYwFAYDVQQIEw1Ob29yZCBIb2xsYW5kMRIwEAYDVQQHEwlBbXN0ZXJkYW0xDzANBgNVBAoUBjElQ2x1YjEiMCAGA1UEAxMZc3RyZWFtLm9uZXBlcmNlbnRjbHViLmNvbTEpMCcGCSqGSIb3DQEJARYaZGV2dGVhbUBvbmVwZXJjZW50Y2x1Yi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvhS960dQQISseIN3ZAW2nUZok5nFVmseKoBwA+TssOeaWwHe//2DJaiJlFqE26VcN4XIrnUru9q0hDGgeLDwX2/g3y43LtFgVag3eWLRAnmP8opvwALN1YDRPHcWS00koCdnmtrRdkefA+5pjQc01lXAnrCrTFU/qSbKkGGwbGpoc3uzqb7d+KgpHJyTyNhVN+ac7XdCg2EVWSg3VCUEqKRk7EXo/H2at8EEuOnrJwd3nGJON6GY+lWEqDAd29jz9uFSGGGCxWRPPr1EJj6U7HpffsL1Cl7tSrlWeE1/2uOnXUSceKCwYOvcDIvzVQLXPadvPH8OQJg7dSgPukgZbAgMBAAGjggEBMIH+MB0GA1UdDgQWBBQoHEToHyvXLxLyYQipE6n6bWEmQDCBzgYDVR0jBIHGMIHDgBQoHEToHyvXLxLyYQipE6n6bWEmQKGBn6SBnDCBmTELMAkGA1UEBhMCTkwxFjAUBgNVBAgTDU5vb3JkIEhvbGxhbmQxEjAQBgNVBAcTCUFtc3RlcmRhbTEPMA0GA1UEChQGMSVDbHViMSIwIAYDVQQDExlzdHJlYW0ub25lcGVyY2VudGNsdWIuY29tMSkwJwYJKoZIhvcNAQkBFhpkZXZ0ZWFtQG9uZXBlcmNlbnRjbHViLmNvbYIJAJfvTxG/az/FMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBAIkr8M21/Jyd/d+ZyvJfjZ/QgZp41RJGVVnLQ3eQC8cCqPqF/Cpc1Tt4ayaZhgyJxmcfKoM1ssgKAnjeyCodGxlJ1ai+LViQoYJuslu05i6MC9QUHxSncucjtlYL7K0rHegDR3wLd8XOCB7zgR74LpCpINRu2LbODI8jLBGkevOCBwztpRLgoqq3qNYus5VHUvtrlQW+3MmFKNDkLnRs8AJdlewQUuRdPdTKMBfvPIao2Kl15XTTpTN+lUALLstMFPrV9gHjWBwVzlPAwvIw7x0271/vm6oFCa44+1wmkrLj9eyhX+Jse12UZtXlpJzY4yVqGqoFTJLDOPHmvNg+uDM=
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://stream.onepercentclub.com/sso/saml/?sls"/>
<md:NameIDFormat>
urn:oasis:names:tc:SAML:2.0:nameid-format:unspecified
</md:NameIDFormat>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://stream.onepercentclub.com/sso/saml/?acs" index="1"/>
</md:SPSSODescriptor>
<md:Organization>
<md:OrganizationName xml:lang="en-US">1%Club</md:OrganizationName>
<md:OrganizationDisplayName xml:lang="en-US">One Percent Club</md:OrganizationDisplayName>
<md:OrganizationURL xml:lang="en-US">http://onepercentclub.com</md:OrganizationURL>
</md:Organization>
<md:ContactPerson contactType="technical">
<md:GivenName>Dev Team</md:GivenName>
<md:EmailAddress>devteam@onepercentlcub.com</md:EmailAddress>
</md:ContactPerson>
<md:ContactPerson contactType="support">
<md:GivenName>Dev Team</md:GivenName>
<md:EmailAddress>devteam@onepercentlcub.com</md:EmailAddress>
</md:ContactPerson>
</md:EntityDescriptor>
