language: python
sudo: false
cache:
  directories:
  - $HOME/.pip-cache/
python:
- '2.7.9'
env:
  matrix:
  - DJANGO=django==1.6.8
  - DJANGO=django==1.9.6
addons:
  apt:
    packages:
    - libxmlsec1
    - libxmlsec1-dev
    - libxml2
    - libxslt1-dev
    - swig
install:
- pip install --upgrade setuptools pip --use-mirrors
- pip install flake8 lxml
- pip install Django==$DJANGO
- pip install -e .[test] --process-dependency-links
before_script:
    flake8 .
script:
- python ./setup.py test
