language: python
sudo: false
python:
- '2.7.9'
cache: pip
  - "$HOME/.cache/pip/"
  - "$HOME/virtualenv/python2.7.9/lib/python2.7/site-packages"
env:
  matrix:
  - DJANGO=django==1.9.6"
addons:
  apt:
    packages:
    - libxmlsec1
    - libxmlsec1-dev
    - libxml2
    - libxslt1-dev
    - swig
install:
- pip install --upgrade setuptools pip
- pip install flake8 lxml==4.2.2
- pip install -e .[test] --process-dependency-links
before_script:
    flake8 .
script:
- python ./setup.py test
